### ISSUE TITLE
Report state

### ISSUE THREAD

**Issue by pajeronda** [tsprlng/nad-link#5]
Hi @tsprlng 

I don't know if you still have this wonderful vintage amplifier, but I do and I am looking for information on the nad-link protocol to know if it reports the status of the amplifier and connected devices (e.g., the cd payer).

**Comment by tsprlng** [comment]
I use it every day :). Unfortunately I can't immediately help with your info quest as I don't have any other NAD gear except the amp, and don't know anything beyond what I got from the ancient websites at the time.

The design seems relatively simple overall, so if I had to guess, I suspect it will only pick up the infrared remote and relay it out to other components. I've never hooked up a scope to it to check if it's doing anything else though. Might try that soon and just flip between sources to see if it sends anything. There's not much else to try. Pretty sure it couldn't report the volume level for example.

I'll let you know if I find out anything different, otherwise good luck!
